apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: catalogue-$CLUSTER_NAME
    cloudProvider: $CLUSTER_NAME
  name: catalogue-$CLUSTER_NAME
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: catalogue-service-$CLUSTER_NAME,catalogue-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: clusterName:$CLUSTER_NAME;service:catalogue
    - name: MONGO_HOST
      value: mongodb-$CLUSTER_NAME
    image: mehreentahir/rs-catalogue:latest
    name: catalogue-$CLUSTER_NAME
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudProvider: $CLUSTER_NAME
  name: catalogue-$CLUSTER_NAME
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: catalogue-$CLUSTER_NAME
status:
  loadBalancer: {}
