apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: loader-$CLUSTER_NAME
    cloudProvider: $CLUSTER_NAME
  name: loader-$CLUSTER_NAME
spec:
  containers:
  - env:
    - name: HOST
      value: $PUBLIC_URL
    - name: CLIENTS
      value: "$CLIENTS"
    image: $DOCKERHUB_USER/rs-loader:$TAG
    name: loader-$CLUSTER_NAME
    resources: {}
  restartPolicy: OnFailure
status: {}
