apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: payment-$CLUSTER_NAME
    cloudProvider: $CLUSTER_NAME
  name: payment-$CLUSTER_NAME
spec:
  containers:
  - env:
    - name: NEW_RELIC_APP_NAME
      value: payment-service-$CLUSTER_NAME;payment-service
    - name: NEW_RELIC_LICENSE_KEY
      value: $NEW_RELIC_LICENSE_KEY
    - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
      value: "true"
    - name: NEW_RELIC_LABELS
      value: clusterName:$CLUSTER_NAME;service:payment
    - name: CART_HOST
      value: cart-$CLUSTER_NAME
    - name: USER_HOST
      value: user-$CLUSTER_NAME
    - name: AMQP_HOST
      value: rabbitmq-$CLUSTER_NAME
    image: mehreentahir/rs-payment:latest
    name: payment-$CLUSTER_NAME
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cloudProvider: $CLUSTER_NAME
  name: payment-$CLUSTER_NAME
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: payment-$CLUSTER_NAME
status:
  loadBalancer: {}